name: Release

on:
  push:
    tags:
    - 'v*'

env:
  GOPATH: ${{ github.workspace }}/..

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:

    - uses: actions/setup-go@v3
      with:
        go-version: 1.x

    - uses: actions/checkout@v3

    - name: Install tools
      run: |
        mkdir -p $(go env GOPATH)/bin/
        go install github.com/Songmu/goxz/cmd/goxz@v0.9.1
        go install github.com/tcnksm/ghr@v0.16.0

    - name: Build release binaries
      run: |
        echo ${GITHUB_REF##*/}
        goxz -d goxz -pv ${GITHUB_REF##*/} -os windows,linux,darwin -arch=amd64
        goxz -d goxz -pv ${GITHUB_REF##*/} -os linux,darwin -arch=arm64

    - name: Create a release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') }}

    - name: Upload binaries to the release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ghr ${GITHUB_REF##*/} goxz

# based on: github.com/koron-go/_skeleton/.github/workflows/release.yml
